version: "3.8"

services:
  sniper:
    build: .
    restart: unless-stopped
    ports:
      - "10000:10000"   # API Flask / Telegram Webhook
      - "8000:8000"     # Métricas Prometheus
    environment:
      - RPC_URL=${RPC_URL}
      - CHAIN_ID=${CHAIN_ID}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - DRY_RUN=${DRY_RUN}
      - DISCOVERY_INTERVAL=${DISCOVERY_INTERVAL}
      - TRADE_SIZE_ETH=${TRADE_SIZE_ETH}
      - MIN_LIQ_WETH=${MIN_LIQ_WETH}
      - TAKE_PROFIT_PCT=${TAKE_PROFIT_PCT}
      - STOP_LOSS_PCT=${STOP_LOSS_PCT}
      - EXIT_POLL_INTERVAL=${EXIT_POLL_INTERVAL}
      - DEX_1_NAME=${DEX_1_NAME}
      - DEX_1_FACTORY=${DEX_1_FACTORY}
      - DEX_1_ROUTER=${DEX_1_ROUTER}
      - DEX_1_TYPE=${DEX_1_TYPE}
    volumes:
      - ./positions.db:/app/positions.db
    healthcheck:
      test: ["CMD-SHELL","curl -fs http://localhost:8000/metrics || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
